### ISSUE TITLE
醸造を行うための準備が完了

### ISSUE THREAD

**Issue by typeriver** [waprojecthq/wanone#390]
以下が決まって、準備ができている

- [ ] 　期間
- [ ] 　滞在するところ
- [ ] 　岡山での移動手段
- [ ] 　海士町の畑をあけてもいい状態

**Comment by hsgwshion** [comment]
- [ ] 今年度の醸造においてプレス方法が大岡さんと合意が取れている
- [ ] 海士町での具体的な醸造手法を決めるために必要な論点が明確になっている
